### PR TITLE
feat: add Vimeo support

### PR DESCRIPTION
**Pull request by ferrarafer**
- Added pod_player package
- Added VimeoPlayer common widget
- Updated CourseLandingTrailer widget
- Fixed issue with sync function inside async function

https://user-images.githubusercontent.com/1505545/227757234-b1fdcf3c-ca6d-487c-b14d-2397048bbb65.mp4

### CODE REVIEW

**Review by FilledStacks — CHANGES_REQUESTED** [review]
That's what I'm talking about man! This is awesome. 

Requesting changes for 2 reasons:
- Resolve the conflict after merging in the 404 work
- Are we certain that this works with privately hosted videos on vimeo that's not public?

**Review by FilledStacks — APPROVED** [review]

**Comment by FilledStacks** [comment]
@ferrarafer resolve the conflicts then we should be good to go

**Comment by ferrarafer** [comment]
> * Are we certain that this works with privately hosted videos on vimeo that's not public?

Not yet :disappointed_relieved:, we need to dig deeper with it.

**Comment by ferrarafer** [comment]
> @ferrarafer resolve the conflicts then we should be good to go

Conflicts resolved ✅

**Comment by FilledStacks** [comment]
Awesome. It's merged. I'll keep this branch available for comparison of the code later.

**Pull request merged**
